---
title: "Tidy Tuesday 2021"
subtitle: "Week 11"
output: github_document
author: "Lorena Abad"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
options(width=80)
knitr::opts_chunk$set(
  echo = TRUE,
  dev="CairoPNG", 
  warning = F, message = F, cache = F, 
  fig.showtext = T,
  tidy.opts=list(width.cutoff=80), 
  tidy=TRUE
)
```

# Tidy Tuesday week 11

## Get data

```{r}
library(tidytuesdayR)
tuesdata <- tt_load(2021, week = 11)
```

## Explore

```{r}
library(tidyverse)
bechdel = tuesdata$raw_bechdel
imdb = tuesdata$movies
bechdel %>% glimpse()
imdb %>% glimpse()
```

```{r}
oscars = imdb %>% 
  mutate(awards = na_if(awards, "N/A")) %>% 
  select(year, imdb_id, title, clean_test, binary, awards) %>% 
  separate(awards,
           sep = "\\. ",
           into = c("big_wins_nominations", "wins_nominations"),
           fill = "left",
           remove = T) %>% 
  filter(str_detect(big_wins_nominations, "Oscar")) %>% 
  mutate(
    oscar_win = ifelse(str_detect(big_wins_nominations, "Won"), T, F),
    oscar_nom = ifelse(str_detect(big_wins_nominations, "Nominated"), T, F),
    oscar_no = as.numeric(str_extract(big_wins_nominations, "\\d+"))
  ) %>% 
  mutate(
    clean_test = factor(
      clean_test,
      levels =  c('ok', 'dubious', 'men', 'notalk', 'nowomen'),
      labels = c("Pass", "Dubious", "Women only talk about men",
                 "Women don't talk to each other",
                 "Fewer than two named women")
    )
  ) 

oscars_summary = oscars %>% 
  group_by(clean_test, oscar_win, oscar_nom) %>% 
  summarize(
    count_movies = n(),
    count_oscars = sum(oscar_no),
    binary = first(binary)
  ) %>% 
  ungroup() %>% 
  group_by(oscar_win) %>% 
  mutate(perc_movies = count_movies/sum(count_movies)) %>% 
  ungroup() %>% 
  mutate(oscars = case_when(oscar_win~"Wins",TRUE~"Nominations"))
```

## Plot

```{r, fig.showtext=T}
# Load fonts
extrafont::loadfonts('win')
# Oscars color palette
colors = c("#BD0628","#800155","#8C416B","#AF89AD","#FF9400")
p = ggplot(oscars_summary) +
  geom_vline(aes(xintercept = 0.5), linetype = "longdash", 
             size = 0.8, color = "grey50") +
  geom_col(
    aes(y = oscars, x = perc_movies, fill = clean_test), 
    alpha = 0.85, show.legend = T, color = "white"
  ) +
  scale_x_continuous(
    expand = c(0,0),
    labels = scales::percent,
    sec.axis = dup_axis(trans = rev)
  ) +
  scale_y_discrete(expand = c(0.3, 0.2)) +
  scale_fill_manual(
    "",
    values = rev(colors)
  ) +
  labs(
    title = "The Oscars and the Bechdel Test",
    subtitle = "Percentage of films between 1971 and 2013 that were nominated or won\nan academy award and their Bechdel Test result.",
    caption = "Data: FiveThirtyEight. Visualization: @loreabad6"
  ) +
  theme_minimal() +
  theme(
    axis.title = element_blank(),
    axis.text.x = element_text(size = 9),
    text = element_text(family = "Futura LT", size = 13), 
    panel.background = element_rect(
      fill = "grey80", color = "transparent"
    ),
    plot.background = element_rect(
      fill = "grey80", color = "transparent"
    ),
    plot.subtitle = element_text(size = 12), 
    plot.caption = element_text(hjust = 0, size = 8),
    panel.grid = element_blank()
  )
```

## Save plot
```{r, fig.showtext=T}
ggsave(p, filename = "plot/2021_week_11.png", device = "png", width = 25, height = 12, units = "cm", dpi = 300)
knitr::plot_crop("plot/2021_week_11.png")
```