---
title: "Tidy Tuesday 2020"
subtitle: "Week 39"
output: github_document
author: "Lorena Abad"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev="CairoPNG", warning = F, message = F, cache = F, fig.showtext = T)
```

# Tidy Tuesday week 39

## Get data

```{r}
library(tidytuesdayR)
tuesdata <- tidytuesdayR::tt_load(2020, week = 39)
```

## Explore

```{r}
library(dplyr)
tuesdata$peaks %>% glimpse()
tuesdata$members %>% glimpse()
```


```{r}
women_peaks = tuesdata$members %>% 
  filter(sex == 'F') %>% 
  inner_join(tuesdata$peaks %>% filter(peak_name=='Everest')) %>% 
  mutate(highpoint_metres = ifelse(is.na(highpoint_metres),4500,highpoint_metres))

women_year = women_peaks %>% 
  group_by(highpoint_metres, year) %>% 
  summarise(n = n())

extrafont::loadfonts(device = 'win')
```

```{r}
p1 = ggplot(women_peaks) +
  geom_bar(aes(age, fill =..count..), color = NA, show.legend = F) +
  scico::scale_fill_scico(palette = 'acton', end = 0.7) +
  scale_x_continuous('', n.breaks = 8) +
  scale_y_continuous('', expand = c(0,0)) +
  annotate(geom = 'text', x = 65, y = 50, color = 'grey30', family = 'Monotype Corsiva', size = 4.5, label = 'Age') +
  theme(
    panel.background = element_rect(fill = 'transparent'),
    plot.background = element_rect(fill = 'transparent', color = 'transparent'),
    panel.border = element_blank(),
    panel.grid = element_blank(),
    # plot.title = element_text(hjust = 1, ), 
    axis.ticks = element_blank(),
    axis.text = element_text(color = 'grey60', size = 7)
  ) 

p1 = ggplotGrob(p1)
```


```{r, fig.height=6, fig.width=8, fig.showtext=T}
library(ggplot2)
library(ggimage)
library(magick)
library(ggtext)

p = ggplot(women_year, aes(y = highpoint_metres, x = year, color = n)) +
  geom_point(shape = 16, size = 1.5) +
  geom_vline(aes(xintercept = 1953), color = 'grey60', linetype = 'longdash') +
  geom_text(aes(label = 'First successful ascent: 1953', x = 1953, y = 7600), angle = 90, size = 3, nudge_x = -1, color = 'grey50') +
  scale_y_continuous(
    position = 'right', 
    breaks = c(4500, 5000, 6000, 7000, 8000, 8850), 
    labels = c('No highpoint data', '5000 m', '6000 m', '7000 m', '8000 m', '8850 m - Summit')
  ) +
  annotation_custom(grob = p1, xmin = 2010, xmax = 2035, ymin = 8800, ymax = 10200) +
  scale_x_continuous(n.breaks = 7) +
  scale_color_viridis_c(
    'No. of women', option = 'magma', 
    n.breaks = 5, direction = -1, end = 0.8,
    guide = guide_colorsteps(
      barheight = unit(2, 'mm'), 
      show.limits = T, title.position = 'top'
  )) +
  labs(
    title = "Women on top of the world!",
    subtitle = "From 1950 to 2019, <span style='color:#8C2981FF'>**1760 women**</span> attempted to climb<br>the highest peak in the world, **Mount Everest**. That is <br>8% of all climbing attempts. <span style='color:#8C2981FF'>**699 women**</span> have made<br>the summit, i.e. 7% of all the recorded summits.",
    caption = "Data: The Himalayan Database. Created by: @loreabad6", 
    x = 'Year of attempt', y = 'Highpoint reached'
  ) +
  theme(
    title = element_text(color = 'grey30', family = 'Monotype Corsiva', size = 12),
    axis.text = element_text(color = 'grey50'),
    legend.text = element_text(color = 'grey50'),
    legend.title.align = 0.5,
    legend.position = c(0.72, 1.1),
    legend.direction = 'horizontal',
    panel.grid.major = element_line(linetype = 'dashed', size = 0.5),
    panel.grid.minor = element_blank(),
    axis.ticks = element_blank(),
    plot.title = element_text(size = 18),
    plot.subtitle = element_markdown(family = 'sans', size = 10), 
    plot.caption = element_text(family = 'sans', hjust = 0, size = 8)
  )

(p2 = ggbackground(
  p, 'img/week39_everest.png',
  image_fun = function(x) image_colorize(x, opacity = 85, color = 'white')
  ))
```

## Save plot
```{r, fig.showtext=T}
ggsave(p2, filename = "plot/2020_week_39.png", device = "png", width = 18, height = 14, units = "cm")
```