---
title: "Tidy Tuesday 2020"
subtitle: "Week 41"
output: github_document
author: "Lorena Abad"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev="CairoPNG", warning = F, message = F, cache = F, fig.showtext = T)
```

# Tidy Tuesday week 41

## Get data

```{r}
library(tidytuesdayR)
tuesdata <- tidytuesdayR::tt_load(2020, week = 41)
```

## Explore

```{r}
library(dplyr)
tuesdata$tournament %>% glimpse()

champions = tuesdata$tournament %>% 
  filter(tourney_finish == 'Champ') %>% 
  group_by(school) %>%
  mutate(champ_wins =n()) 
```

```{r}
windows()
# Load fonts
emojifont::load.emojifont(font = "OpenSansEmoji.ttf")
```


```{r, fig.showtext=T}
library(ggplot2)
library(emojifont)
p = ggplot(champions, aes(x = year, y = reorder(school, champ_wins))) +
  # geom_point() +
  emojifont::geom_emoji(
    alias = 'basketball',
    x = champions$year,
    y = reorder(champions$school,champions$champ_wins),
    size = 16, color = '#D44500', vjust = 0.1
  ) +
  labs(
    x = '', y = '',
    title = "NCAA Women's Basketball Champions", 
    subtitle = "1982-2018",
    caption = "Data: FiveThirtyEight. Visualization: @loreabad6"
  ) +
  scale_x_continuous(breaks = seq(1982, 2018, 2)) +
  theme_bw() +
  theme(
    text = element_text(family = "mono", size = 30),
    panel.grid = element_line(size = 0.35)
  )
```

## Save plot
```{r, fig.showtext=T}
ggsave(p, filename = "plot/2020_week_41.png", device = "png", width = 25, height = 12, units = "cm", dpi = 300)
```