---
title: "Tidy Tuesday 2020"
subtitle: "Week 38"
output: github_document
author: "Lorena Abad"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev="CairoPNG", warning = F, message = F, cache = T, fig.showtext = T)
```

# Tidy Tuesday week 38

## Get data

```{r}
library(tidytuesdayR)
tuesdata <- tidytuesdayR::tt_load(2020, week = 38)
```

## Explore

```{r}
library(dplyr)
tuesdata$kids %>% glimpse()
```

After reading the `tidykids` site, I decided to go for parks and recreations investment per child adjusted for inflation. 

```{r}
parkrec = tuesdata$kids %>% 
  filter(variable == 'parkrec') %>% 
  select(-raw, -inf_adj)

parkrec
```

```{r}
library(tigris)
states = states()
states

parkrec_states = states %>% right_join(parkrec, by = c('NAME'='state'))
```

```{r, fig.height=6, fig.width=8, fig.showtext=T}
extrafont::loadfonts(device = 'win')
library(ggplot2)
library(geofacet)
g = ggplot(parkrec_states, aes(x = year, y = inf_adj_perchild, color = inf_adj_perchild),) +
  geom_line(size = 2.5, alpha = 0.1) +
  geom_line(size = 1) + 
  facet_geo(~STUSPS) +
  scale_color_viridis_c('', limits = c(0,1.5), breaks = c(0,0.5,1,1.5),
                        labels = paste(c(0.0,0.5,1.0,1.5), '$')) +
  xlab('') + ylab('') +
  labs(
    title = 'The pulse of parks and recreation',
    subtitle = 'Public spending on parks and recreation\nper child from 1997 to 2016\nadjusted for inflation',
    caption = "Data: {tidykids} R package. Created by: @loreabad6"
  ) +
  guides(color = guide_colorbar(label.position = 'top')) +
  theme(
    text = element_text(family = 'Futura LT', color = 'white'),
    strip.background = element_blank(),
    title = element_text(family = 'Segoe Print'),
    strip.text = element_text(color = 'white'),
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.position = c(0.8,1.17),
    legend.direction = 'horizontal',
    panel.background = element_rect(fill = 'transparent'),
    plot.background = element_rect(fill = 'black', color = 'transparent'),
    panel.grid = element_blank(),
    legend.background = element_rect(fill = 'transparent'),
    legend.key.width = unit(8, units = "mm"),
    legend.key.height = unit(2, units = "mm")
  )

g
```

## Save plot
```{r, fig.showtext=T}
ggsave(g, filename = "plot/2020_week_38.png", device = "png", width = 18, height = 15, units = "cm")
```