---
title: "Tidy Tuesday 2020"
subtitle: "Week 43"
output: github_document
author: "Lorena Abad"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev="CairoPNG", warning = F, message = F, cache = F, fig.showtext = T)
```

# Tidy Tuesday week 43

## Get data

```{r}
library(tidytuesdayR)
tuesdata <- tidytuesdayR::tt_load(2020, week = 43)
```

## Explore

```{r}
library(dplyr)
tuesdata$beer_awards %>% glimpse()
beer = tuesdata$beer_awards
```

## After playing with the data, I wanted to find the answer to a very important question:
## Where do I get the best Belgium style beer in the U.S.?

```{r}
# Get states polygons
library(tidygeocoder)

# Extract only Belgium beer style
beer_belg = beer %>% 
  filter(grepl("Belg", category)) 

# Get Lat/Long coordinates for the wining cities
beer_geocode = beer_belg %>% 
  geocode(city = city, state = state, 
          method = 'osm', 
          lat = latitude , long = longitude)

# Convert into sf object 
library(sf)
beer_sf = beer_geocode %>% 
  st_as_sf(coords = c('longitude', 'latitude'))
```

```{r}
library(ggplot2)

beer_belg %>% 
  group_by(state, medal) %>% 
  summarize(count = n()) %>% 
  filter(medal == 'Gold') %>% 
  arrange(desc(count))

beer_belg %>% 
  group_by(state) %>% 
  mutate(prizes_per_state = n()) %>% 
  ggplot(aes(x = year, y = reorder(state, prizes_per_state), color = medal)) +
  geom_point()
  
```
