---
title: "Tidy Tuesday 2022"
subtitle: "Week 02"
output: github_document
author: "Lorena Abad"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
options(width=80)
knitr::opts_chunk$set(
  echo = TRUE,
  dev="CairoPNG", 
  warning = F, message = F, cache = F, 
  fig.showtext = T,
  tidy.opts=list(width.cutoff=80), 
  tidy=TRUE
)
```

# Tidy Tuesday week 02

## Get data

```{r}
library(tidytuesdayR)
tuesdata = tt_load("2022-01-11")
```

## Explore

```{r}
library(tidyverse)
colony = tuesdata$colony
stressor = tuesdata$stressor
colony %>% glimpse()
stressor %>% glimpse()
```

```{r}
colony = colony %>% 
  mutate(
    months = case_when(
      months == 2019 ~ "April-June",
      TRUE ~ months
    ),
    year = case_when(
      year == '6/' ~ "2019",
      TRUE ~ year
    )
  ) %>% 
  group_by(year) %>% 
  mutate(colony_lost_year = sum(colony_lost, na.rm = TRUE)) %>% 
  ungroup()

stressor = stressor %>% 
  mutate(
    months = case_when(
      months == 2019 ~ "April-June",
      TRUE ~ months
    ),
    year = case_when(
      year == '5/' ~ "2019",
      TRUE ~ year
    )
  )
bees = left_join(colony, stressor)

colony_test = colony %>% 
  group_by(year, months) %>% 
  summarise(total = sum(colony_lost))

bees_sum = bees %>% 
  group_by(year, months, stressor) %>% 
  mutate(
    colony_lost_stress = colony_lost * (stress_pct/100),
    year = as.numeric(year)
  ) %>% 
  summarise(
    total_colony_lost_stress = sum(colony_lost_stress, na.rm = TRUE)
  ) 
```

## Plot

```{r, fig.showtext=T}
library(scico)
library(svgparser)

beesvg = here::here("img/bee.svg")
beesvgtext = paste(readLines(beesvg), collapse = "\n")

# Load fonts
extrafont::loadfonts('win')

# Bee svg
ggplot(bees_sum) +
  aes(
    x = year, 
    y = total_colony_lost_stress/1000,
    fill = fct_relevel(months, "April-June", after = 1),
    color = fct_relevel(months, "April-June", after = 1)
    ) +
  geom_col(
    position = position_dodge2(preserve = "single"),
    width = 1
  ) +
  scale_x_continuous(n.breaks = 7) +
  scale_fill_scico_d(
    "",
    aesthetics = c("color", "fill"),
    palette = "lajolla", direction = -1,
    begin = 0.2, end = 0.7
  ) +
  facet_wrap(
    ~fct_reorder(
      stressor,
      total_colony_lost_stress,
      .desc = TRUE
      )
  ) +
  labs(
    x = NULL, y = NULL,
    title = "Honey bee colony loss", 
    subtitle = "Colony stressors in the United States from 2015 to 2021\nAbsolute loss per thousand colonies in y-axis",
    caption = "Data: USDA. Visualization: @loreabad6"
  ) +
  theme_minimal() +
  theme(
    text = element_text(
      # family = "Sylfaen",
      family = "Niagara",
      size = 14,
      color = scico(1, direction = -1, end = 0.9, palette = "lajolla")
    ),
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5),
    plot.caption = element_text(size = 9),
    legend.position = "top",
    legend.key.size = unit(3, "mm"),
    plot.background = element_rect(fill = "#f3f6f4")
  )
```

## Save plot
```{r, fig.showtext=T}
ggsave(filename = "plot/2022_week_02.png", device = "png", width = 30, height = 12, units = "cm", dpi = 300)
```